/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PointRouteImport } from './routes/point'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssociateRouteImport } from './routes/_authenticated/associate'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedHostRouteImport } from './routes/_authenticated/host'
import { Route as PaseRefRouteImport } from './routes/pase.$ref'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnfitrionesRouteImport } from './routes/_authenticated/admin.anfitriones'
import { Route as AuthenticatedAdminFacturacionRouteImport } from './routes/_authenticated/admin.facturacion'
import { Route as AuthenticatedAdminIntercambiosRouteImport } from './routes/_authenticated/admin.intercambios'
import { Route as AuthenticatedAdminLlavesRouteImport } from './routes/_authenticated/admin.llaves'
import { Route as AuthenticatedAdminProRouteImport } from './routes/_authenticated/admin.pro'
import { Route as AuthenticatedAdminPuntosRouteImport } from './routes/_authenticated/admin.puntos'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PointRoute = PointRouteImport.update({
  id: '/point',
  path: '/point',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssociateRoute = AuthenticatedAssociateRouteImport.update({
  id: '/associate',
  path: '/associate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostRoute = AuthenticatedHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PaseRefRoute = PaseRefRouteImport.update({
  id: '/pase/$ref',
  path: '/pase/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnfitrionesRoute =
  AuthenticatedAdminAnfitrionesRouteImport.update({
    id: '/anfitriones',
    path: '/anfitriones',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFacturacionRoute =
  AuthenticatedAdminFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntercambiosRoute =
  AuthenticatedAdminIntercambiosRouteImport.update({
    id: '/intercambios',
    path: '/intercambios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLlavesRoute =
  AuthenticatedAdminLlavesRouteImport.update({
    id: '/llaves',
    path: '/llaves',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProRoute = AuthenticatedAdminProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPuntosRoute =
  AuthenticatedAdminPuntosRouteImport.update({
    id: '/puntos',
    path: '/puntos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/login': typeof LoginRoute
  '/point': typeof PointRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/associate': typeof AuthenticatedAssociateRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/host': typeof AuthenticatedHostRoute
  '/pase/$ref': typeof PaseRefRoute
  '/admin/anfitriones': typeof AuthenticatedAdminAnfitrionesRoute
  '/admin/facturacion': typeof AuthenticatedAdminFacturacionRoute
  '/admin/intercambios': typeof AuthenticatedAdminIntercambiosRoute
  '/admin/llaves': typeof AuthenticatedAdminLlavesRoute
  '/admin/pro': typeof AuthenticatedAdminProRoute
  '/admin/puntos': typeof AuthenticatedAdminPuntosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/login': typeof LoginRoute
  '/point': typeof PointRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/associate': typeof AuthenticatedAssociateRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/host': typeof AuthenticatedHostRoute
  '/pase/$ref': typeof PaseRefRoute
  '/admin/anfitriones': typeof AuthenticatedAdminAnfitrionesRoute
  '/admin/facturacion': typeof AuthenticatedAdminFacturacionRoute
  '/admin/intercambios': typeof AuthenticatedAdminIntercambiosRoute
  '/admin/llaves': typeof AuthenticatedAdminLlavesRoute
  '/admin/pro': typeof AuthenticatedAdminProRoute
  '/admin/puntos': typeof AuthenticatedAdminPuntosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/login': typeof LoginRoute
  '/point': typeof PointRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/associate': typeof AuthenticatedAssociateRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/host': typeof AuthenticatedHostRoute
  '/pase/$ref': typeof PaseRefRoute
  '/_authenticated/admin/anfitriones': typeof AuthenticatedAdminAnfitrionesRoute
  '/_authenticated/admin/facturacion': typeof AuthenticatedAdminFacturacionRoute
  '/_authenticated/admin/intercambios': typeof AuthenticatedAdminIntercambiosRoute
  '/_authenticated/admin/llaves': typeof AuthenticatedAdminLlavesRoute
  '/_authenticated/admin/pro': typeof AuthenticatedAdminProRoute
  '/_authenticated/admin/puntos': typeof AuthenticatedAdminPuntosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/login'
    | '/point'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/associate'
    | '/checkout'
    | '/host'
    | '/pase/$ref'
    | '/admin/anfitriones'
    | '/admin/facturacion'
    | '/admin/intercambios'
    | '/admin/llaves'
    | '/admin/pro'
    | '/admin/puntos'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/login'
    | '/point'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/associate'
    | '/checkout'
    | '/host'
    | '/pase/$ref'
    | '/admin/anfitriones'
    | '/admin/facturacion'
    | '/admin/intercambios'
    | '/admin/llaves'
    | '/admin/pro'
    | '/admin/puntos'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/buscar'
    | '/login'
    | '/point'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/associate'
    | '/_authenticated/checkout'
    | '/_authenticated/host'
    | '/pase/$ref'
    | '/_authenticated/admin/anfitriones'
    | '/_authenticated/admin/facturacion'
    | '/_authenticated/admin/intercambios'
    | '/_authenticated/admin/llaves'
    | '/_authenticated/admin/pro'
    | '/_authenticated/admin/puntos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BuscarRoute: typeof BuscarRoute
  LoginRoute: typeof LoginRoute
  PointRoute: typeof PointRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PaseRefRoute: typeof PaseRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/point': {
      id: '/point'
      path: '/point'
      fullPath: '/point'
      preLoaderRoute: typeof PointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/associate': {
      id: '/_authenticated/associate'
      path: '/associate'
      fullPath: '/associate'
      preLoaderRoute: typeof AuthenticatedAssociateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host': {
      id: '/_authenticated/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof AuthenticatedHostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pase/$ref': {
      id: '/pase/$ref'
      path: '/pase/$ref'
      fullPath: '/pase/$ref'
      preLoaderRoute: typeof PaseRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/anfitriones': {
      id: '/_authenticated/admin/anfitriones'
      path: '/anfitriones'
      fullPath: '/admin/anfitriones'
      preLoaderRoute: typeof AuthenticatedAdminAnfitrionesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/facturacion': {
      id: '/_authenticated/admin/facturacion'
      path: '/facturacion'
      fullPath: '/admin/facturacion'
      preLoaderRoute: typeof AuthenticatedAdminFacturacionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/intercambios': {
      id: '/_authenticated/admin/intercambios'
      path: '/intercambios'
      fullPath: '/admin/intercambios'
      preLoaderRoute: typeof AuthenticatedAdminIntercambiosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/llaves': {
      id: '/_authenticated/admin/llaves'
      path: '/llaves'
      fullPath: '/admin/llaves'
      preLoaderRoute: typeof AuthenticatedAdminLlavesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pro': {
      id: '/_authenticated/admin/pro'
      path: '/pro'
      fullPath: '/admin/pro'
      preLoaderRoute: typeof AuthenticatedAdminProRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/puntos': {
      id: '/_authenticated/admin/puntos'
      path: '/puntos'
      fullPath: '/admin/puntos'
      preLoaderRoute: typeof AuthenticatedAdminPuntosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnfitrionesRoute: typeof AuthenticatedAdminAnfitrionesRoute
  AuthenticatedAdminFacturacionRoute: typeof AuthenticatedAdminFacturacionRoute
  AuthenticatedAdminIntercambiosRoute: typeof AuthenticatedAdminIntercambiosRoute
  AuthenticatedAdminLlavesRoute: typeof AuthenticatedAdminLlavesRoute
  AuthenticatedAdminProRoute: typeof AuthenticatedAdminProRoute
  AuthenticatedAdminPuntosRoute: typeof AuthenticatedAdminPuntosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnfitrionesRoute: AuthenticatedAdminAnfitrionesRoute,
  AuthenticatedAdminFacturacionRoute: AuthenticatedAdminFacturacionRoute,
  AuthenticatedAdminIntercambiosRoute: AuthenticatedAdminIntercambiosRoute,
  AuthenticatedAdminLlavesRoute: AuthenticatedAdminLlavesRoute,
  AuthenticatedAdminProRoute: AuthenticatedAdminProRoute,
  AuthenticatedAdminPuntosRoute: AuthenticatedAdminPuntosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAssociateRoute: typeof AuthenticatedAssociateRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedHostRoute: typeof AuthenticatedHostRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAssociateRoute: AuthenticatedAssociateRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedHostRoute: AuthenticatedHostRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BuscarRoute: BuscarRoute,
  LoginRoute: LoginRoute,
  PointRoute: PointRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PaseRefRoute: PaseRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
