REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_admin() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.my_kiosk_id() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.my_associate_id() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.my_host_id() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_kiosk_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_associate_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_host_id() TO authenticated;